[package]
name = "azoth-examples"
version.workspace = true
edition.workspace = true

[dependencies]
azoth-core.workspace = true
azoth-transform.workspace = true
chrono.workspace = true
hex.workspace = true
serde_json.workspace = true
tokio.workspace = true
